---
- name: Save temporary port
  set_fact:
    configured_port: "{{ ansible_port }}"

- name: Check connection on default SSH port
  wait_for:
    port: "22"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: default_ssh

- name: Set inventory ansible_port to default
  set_fact:
    ansible_port: "22"
  when: 'default_ssh is defined and
          default_ssh.state is defined and
          default_ssh.state == "started"'

- name: If not default port, check if inventory port is available
  wait_for:
    port: "{{ configured_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: configured_ssh
  when: 'default_ssh is defined and
        default_ssh.state is undefined'

- name: SSH already hardened, nothing to do
  debug:
    msg: "SSH port is configured properly"
  when: 'configured_ssh is defined and
        configured_ssh.state is defined and
        configured_ssh.state == "started"'
  register: ssh_port_set

- name: Fail if SSH port was not auto-detected (unknown)
  fail:
    msg: "The SSH port is neither 22 or {{ configured_port }}."
  when: 'ssh_port_set is undefined'

#- name: Confirm host connection works
#  ping:

- name: Setup alternate SSH port
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ hardening_ssh_port }}"
  notify: "Restart sshd"
  become: True

- name: Ensure SSH is reloaded if need be
  meta: flush_handlers

- name: Ensure we use the configured SSH port for the remainder of the role
  set_fact:
    ansible_port: "{{ configured_port }}"

- name: Run deferred setup to gather facts
  setup:
