---


- name: Hardening IPTables | Install iptables persistant
  apt:
    name: iptables-persistent
    state: present
    update_cache: no
  become: True

- name: Hardening IPTables | Copy over base Iptables Rules
  template: src=iptables-rules.j2 dest=/etc/iptables/rules.v4
  notify: restart iptables-persistent
  become: true

- name: Ensure iptables is reloaded
  meta: flush_handlers
