---
# handlers file for hardening

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  become: True

- name: restart iptables-persistent
  service:
    name: netfilter-persistent
    state: restarted
  become: True
