---
# handlers file for hardening

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  become: True

#- name: restart iptables-persistent
#  service:
#    name: netfilter-persistent
#    state: restarted
#  become: True

- name: restart iptables-persistent
  shell: >
    sleep 5s && service iptables-persistent restart
  become: True
  async: 10
  poll: 0
